# NUMPY

In [1]:
import numpy as np
a=np.arange(12)
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [2]:
print(a.ndim)

1


In [3]:
print(a.shape)

(12,)


In [5]:
b=a.reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
print(b.shape)
print(b.ndim)

(3, 4)
2


In [7]:
print("sum of all:",b.sum())

sum of all: 66


In [8]:
print("Row sum:",b.sum(axis=1))

Row sum: [ 6 22 38]


In [9]:
print("Column sum:",b.sum(axis=0))

Column sum: [12 15 18 21]


In [10]:
k=np.arange(11,30)
print(k)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [11]:
k1=np.arange(11,20,3)
print(k1)

[11 14 17]


In [12]:
k2=np.arange(1,2,.3)
print(k2)

[1.  1.3 1.6 1.9]


In [14]:
k3=np.arange(1,2,.01)
print(k3)
print(len(k3))

[1.   1.01 1.02 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11 1.12 1.13
 1.14 1.15 1.16 1.17 1.18 1.19 1.2  1.21 1.22 1.23 1.24 1.25 1.26 1.27
 1.28 1.29 1.3  1.31 1.32 1.33 1.34 1.35 1.36 1.37 1.38 1.39 1.4  1.41
 1.42 1.43 1.44 1.45 1.46 1.47 1.48 1.49 1.5  1.51 1.52 1.53 1.54 1.55
 1.56 1.57 1.58 1.59 1.6  1.61 1.62 1.63 1.64 1.65 1.66 1.67 1.68 1.69
 1.7  1.71 1.72 1.73 1.74 1.75 1.76 1.77 1.78 1.79 1.8  1.81 1.82 1.83
 1.84 1.85 1.86 1.87 1.88 1.89 1.9  1.91 1.92 1.93 1.94 1.95 1.96 1.97
 1.98 1.99]
100


In [15]:
m=np.linspace(1,2,10)
print(m)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [16]:
m=np.linspace(1,2,20)
print(m)

[1.         1.05263158 1.10526316 1.15789474 1.21052632 1.26315789
 1.31578947 1.36842105 1.42105263 1.47368421 1.52631579 1.57894737
 1.63157895 1.68421053 1.73684211 1.78947368 1.84210526 1.89473684
 1.94736842 2.        ]


In [17]:
k=[[1,2],[3,4]]
a=np.array(k)
print(a)

[[1 2]
 [3 4]]


In [18]:
b=np.array([[5,6],[7,8]])
print(b)

[[5 6]
 [7 8]]


In [19]:
print(a+3)

[[4 5]
 [6 7]]


In [20]:
print(a>3)

[[False False]
 [False  True]]


In [21]:
print(a+b)

[[ 6  8]
 [10 12]]


In [22]:
print(a.dot(b))

[[19 22]
 [43 50]]


# PANDAS

In [23]:
import pandas as pd
a=pd.Series()
print(a)

Series([], dtype: float64)


C:\Users\hp\AppData\Local\Temp\ipykernel_12540\684786497.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  a=pd.Series()


In [24]:
b=pd.Series([11,12,13,14])
print(b)

0    11
1    12
2    13
3    14
dtype: int64


In [25]:
c=pd.Series([11,12,13,14],index=['a','b','c','d'])
print(c)

a    11
b    12
c    13
d    14
dtype: int64


In [27]:
d={"id":101,"name":"Priyam","age":21}
d1=pd.Series(d)
print(d1)

id         101
name    Priyam
age         21
dtype: object


In [28]:
s={"names":['Rajesh','Jit','Santanu'],
    "Phys":[34,39,41],
    "Chem":[22,11,22],
    "Math":[20,21,22]}
p=pd.Series(s)
print(p)

names    [Rajesh, Jit, Santanu]
Phys               [34, 39, 41]
Chem               [22, 11, 22]
Math               [20, 21, 22]
dtype: object


In [30]:
d=pd.DataFrame(s)
print(d)

     names  Phys  Chem  Math
0   Rajesh    34    22    20
1      Jit    39    11    21
2  Santanu    41    22    22


In [5]:
import pandas as pd
d={"names":['Rajesh','Jit','Santanu'],
    "Phys":[34,39,41],
    "Chem":[22,11,22],
    "Math":[20,21,22]}
d1=pd.DataFrame(d)
print(d1)
r={"names":"Vipin","Phys":28,"Chem":29,"Math":30}
d2=d1.append(r,ignore_index=True)
print(d2)

     names  Phys  Chem  Math
0   Rajesh    34    22    20
1      Jit    39    11    21
2  Santanu    41    22    22
     names  Phys  Chem  Math
0   Rajesh    34    22    20
1      Jit    39    11    21
2  Santanu    41    22    22
3    Vipin    28    29    30


C:\Users\hp\AppData\Local\Temp\ipykernel_9332\3383399742.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  d2=d1.append(r,ignore_index=True)


In [6]:
d3=d2.pop("Math")
print(d3)
print(d2)

0    20
1    21
2    22
3    30
Name: Math, dtype: int64
     names  Phys  Chem
0   Rajesh    34    22
1      Jit    39    11
2  Santanu    41    22
3    Vipin    28    29


In [7]:
import pandas as pd
df=pd.read_csv('Income_data.csv')
print(df)

       GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528  


In [8]:
df1=df.set_index("State")
print(df1)

                GEOID   2005   2006   2007   2008   2009   2010   2011   2012  \
State                                                                           
Alabama     04000US01  37150  37952  42212  44476  39980  40933  42590  43464   
Alaska      04000US02  55891  56418  62993  63989  61604  57848  57431  63648   
Arizona     04000US04  45245  46657  47215  46914  45739  46896  48621  47044   
Arkansas    04000US05  36658  37057  40795  39586  36538  38587  41302  39018   
California  04000US06  51755  55319  55734  57014  56134  54283  53367  57020   

             2013  
State              
Alabama     41381  
Alaska      61137  
Arizona     50602  
Arkansas    39919  
California  57528  


In [10]:
#Extract Alabama, Alaska, and Arizona for 2005, 2006, 2007
#iloc[start row index:end row index, start column index:end column index]
df2=df1.iloc[ :3, 1:4]
print(df2)

          2005   2006   2007
State                       
Alabama  37150  37952  42212
Alaska   55891  56418  62993
Arizona  45245  46657  47215


In [11]:
#loc[start row name:end column name,start column name:end row name]
df3=df1.loc["Alabama":"Arizona", "2005":"2007"]
print(df3)

          2005   2006   2007
State                       
Alabama  37150  37952  42212
Alaska   55891  56418  62993
Arizona  45245  46657  47215


In [13]:
print("Statewise sum:",df3.sum(axis=1))
print("Yearwise sum:",df3.sum(axis=0))

Statewise sum: State
Alabama    117314
Alaska     175302
Arizona    139117
dtype: int64
Yearwise sum: 2005    138286
2006    141027
2007    152420
dtype: int64


In [15]:
#2005, 2007, 2009
m=df1.iloc[ :3,[1,3,5]]
print(m)

          2005   2007   2009
State                       
Alabama  37150  42212  39980
Alaska   55891  62993  61604
Arizona  45245  47215  45739


In [16]:
n=df1.loc["Alabama":"Arizona", ["2005","2007","2009"]]
print(n)

          2005   2007   2009
State                       
Alabama  37150  42212  39980
Alaska   55891  62993  61604
Arizona  45245  47215  45739


In [17]:
print("Californiawise sum:",df1.sum(axis=1))

Californiawise sum: State
Alabama       370138
Alaska        540959
Arizona       424933
Arkansas      349460
California    498154
dtype: int64


C:\Users\hp\AppData\Local\Temp\ipykernel_9332\4290756627.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("Californiawise sum:",df1.sum(axis=1))


In [20]:
s=df1.iloc[4,1:-1].sum()
print(s)

440626


In [21]:
print(type(s))

<class 'numpy.int64'>


In [2]:
import turtle as t
pen = t.Turtle()
t.bgcolor('#000000')
t.delay(8)
pen.color('#ff0000')
pen.begin_fill()
pen.left(40)
pen.forward(120)
pen.circle(80, 190)
pen.right(100)
pen.circle(80, 180)
pen.forward(160)
pen.left(90)
pen.forward(50)
#pen.setpos(-60, 100)
pen.end_fill()
def txt():
    pen.up()
    pen.setpos(-60, 100)
    pen.color('black')
    pen.write('I Love YOU', font=("Times New Roman", 16))
txt()
pen.end_fill()
t.exitonclick()

Terminator: 

In [ ]:
import turtle as t
pen = t.Turtle()
t.bgcolor('#000000')
t.delay(8)
pen.color('#ff0000')
pen.begin_fill()
pen.left(40)
pen.forward(120)
pen.circle(80, 190)
pen.right(100)
pen.circle(80, 180)
pen.forward(160)
pen.left(90)
pen.forward(50)
#pen.setpos(-60, 100)
pen.end_fill()
def txt():
    pen.up()
    pen.setpos(-60, 100)
    pen.color('black')
    pen.write('I Love YOU', font=("Times New Roman", 16))
txt()
pen.end_fill()
t.exitonclick()